name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "${{ secrets.HEXO_DEPLOY_PRI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --global user.email "${{ secrets.EMAILE }}"
          git config --global user.name "Miseryset"
          git remote rm origin
          git remote add origin git@github.com:Miseryset/AutoGreen.git
          git commit --allow-empty -m "auto green..."
          git push --set-upstream origin main
